[database]
database_url = "postgresql://postgres:postgres@localhost/axum_rest_example_dev"

[http]
listen_address = "0.0.0.0"
listen_port = 8080

[telemetry]
log_format = "full"
opentelemetry = false
