[database]
database_url = "postgres://postgres:postgres@db/axum_rest_example"
min_connections = 8
max_connections = 128
connect_timeout_seconds = 30
idle_timeout_seconds = 900
max_lifetime_seconds = 3600

[http]
listen_address = "0.0.0.0"
listen_port = 8080

[telemetry]
log_format = "json"
opentelemetry = true
opentelemetry_endpoint = "http://otlp:4317"
